Set Stream to main
jquery/ci-management pull request #15
Opened 2020-12-01 21:31 UTC by vvalderrv

Signed-off-by: Vanessa Rene Valderrama <vvalderrama@linuxfoundation.org>

2020-12-01 21:35 UTC, tykeal requested changes

2020-12-01 21:35 UTC, tykeal commented on jjb/ci-management/ci-jobs.yaml
> +      - main:
no need to set branch in the stream (you've got it on the line above) also, no need to do this as an array since you're only doing one stream.

2020-12-02 05:32 UTC, MightyNerdEric requested changes
While testing this, I also found that with the current version of global-jjb, we need `failure-notification` and `failure-notification-prefix` defined in defaults.yaml. The current jjb is invalid.

Take a look at the release notes for v0.57.3: https://docs.releng.linuxfoundation.org/projects/global-jjb/en/latest/release-notes.html#v0-57-3

2020-12-02 05:32 UTC, MightyNerdEric commented on jjb/ci-management/ci-jobs.yaml
> +    stream:
This should just be
`stream: main`

2020-12-02 14:58 UTC, MightyNerdEric approved these changes

2020-12-02 17:07 UTC, tykeal approved these changes

2020-12-02 17:08 UTC, merged