Setup repo administrative files
jquery/ci-management pull request #2
Opened 2020-09-17 19:41 UTC by vvalderrv

Signed-off-by: Vanessa Rene Valderrama <vvalderrama@linuxfoundation.org>

2020-09-17 21:16 UTC, vvalderrv reviewed
This change is not ready to be merged. I'll be submitting another patch based on reviews.

2020-09-18 16:45 UTC, tykeal commented on README.md
> +Login (after requesting membership in group jquery-jenkins-sandbox-access) at the Jenkins sandbox:
A link to https://docs.releng.linuxfoundation.org/en/latest/helpdesk.html should be put in here to help direct people to the support system for requesting sandbox access

2020-09-18 16:47 UTC, tykeal commented on README.md
> +    jenkins-jobs --conf jenkins.ini update jjb your-job-name-here
Change this to:

jenkins-jobs --conf jenkins.ini update -j jjb your-job-name-here

2020-09-18 16:47 UTC, tykeal commented on README.md
> +    jenkins-jobs --conf jenkins.ini update jjb / <job_name>
that / is bad, also you need a -j after update

2020-09-18 16:51 UTC, tykeal requested changes
The check_* files. I don't like that. Those should get moved to global-jjb and have tox reference them from there. This is way too prone to file drift with them as standalone files

See the rest of my inlined comments

2020-09-18 18:52 UTC, tykeal approved these changes

2020-09-18 18:52 UTC, merged